### ISSUE TITLE
Add field to mark a `model` as being `active` (as in deployed and in use) 

### ISSUE THREAD

**Issue by CodeGat** [ACCESS-NRI/experiment-metadb#16]
Sometimes, Releases could be broken, or deprecated, or removed. We still want to keep these in the model provenance DB, but we would like to be able to see if a model is either `active` or `inactive` (or some other words that note that the model is in use or not). 

Could we add a field in the database, `active` (@aidanheerdegen, how's this sound?) that denotes whether a model is currently released and in use? 

We would also have to figure out how to edit the database if a model is deprecated or removed, preferably via a workflow (@CodeGat can help creating this) - can there be an 'API' (similar to how https://github.com/ACCESS-NRI/build-cd/blob/main/tools/release_provenance/test_release_data.json is used by https://github.com/ACCESS-NRI/build-cd/blob/main/tools/release_provenance/save_release.py) that shows what model needs to have their `active` status modified.

**Comment by aidanheerdegen** [comment]
I reckon a `status` field. Options for `status` might be

| Status | Meaning |
|--------|--------|
| `active` | Released and actively available |
| `retracted` | Released and subsequently retracted due to errors |
| ~`deprecated`~ | ~Deprecated release. Not supported may be deleted~ |
| `eol` | End of life. No longer supported |
| `deleted` | End of life release deleted |

But happy to discuss. I'm not sure if we'd ever delete something just because it was old. Seems a bit ... dystopian. But it could happen I guess.

**Comment by aidanheerdegen** [comment]
I guess `deprecated` might be redundant if `eol` is there.

**Comment by CodeGat** [comment]
That's a great idea, having multiple statuses. 
Deleted could be like some kind of cataclysmic scenario where we don't have the `spack.lock` and can't reliably recreate it...I dunno :D

**Comment by aidanheerdegen** [comment]
Yeah `deleted` could be a system shift or some other reason to dump a bunch of old stuff, like reaching some hard limit that is imposed at a later date.

**Comment by aidanheerdegen** [comment]
We could have a `prerelease` status (as you suggested @CodeGat) if we captured *all* builds. I don't see a huge problem with it. It would increase the DB size by 5-10 fold, but it won't be a massive DB. The only question is the utility, and it would likely be pretty niche.

**Comment by CodeGat** [comment]
Closed via https://github.com/ACCESS-NRI/build-cd/pull/108
